#! /bin/sh
export SXHKD_SHELL=/bin/sh

# Start on bspwm boot
sxhkd &
xrdb ~/.Xresources
#sh ~/.refresh_xres.sh &
picom &
#sxhkd -f 100 & 
xwallpaper --stretch ~/at/2.jpg
sh ~/.config/polybar/launch.sh &

bspc monitor DP-2 -n 0 -d 1 2 3 4 5
bspc monitor HDMI-0 -n 1 -d 6 7 8 9 

bspc config border_width         3
bspc config window_gap          26

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#383838"
bspc config focused_border_color "#fba922"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"
bspc config presel_feedback_color "#1ABB9B"
